namespace Bungie.Models
{
    public class MergedStats
    {
        public Stat ActivitiesCleared { get; set; }
        public Stat WeaponKillsSuper { get; set; }
        public Stat ActivitiesEntered { get; set; }
        public Stat WeaponKillsMelee { get; set; }
        public Stat WeaponKillsGrenade { get; set; }
        public Stat AbilityKills { get; set; }
        public Stat Assists { get; set; }
        public Stat TotalDeathDistance { get; set; }
        public Stat AverageDeathDistance { get; set; }
        public Stat TotalKillDistance { get; set; }
        public Stat Kills { get; set; }
        public Stat AverageKillDistance { get; set; }
        public Stat SecondsPlayed { get; set; }
        public Stat Deaths { get; set; }
        public Stat AverageLifespan { get; set; }
        public Stat BestSingleGameKills { get; set; }
        public Stat KillsDeathsRatio { get; set; }
        public Stat KillsDeathsAssists { get; set; }
        public Stat ObjectivesCompleted { get; set; }
        public Stat PrecisionKills { get; set; }
        public Stat ResurrectionsPerformed { get; set; }
        public Stat ResurrectionsReceived { get; set; }
        public Stat Suicides { get; set; }
        public Stat WeaponKillsAutoRifle { get; set; }
        public Stat WeaponKillsFusionRifle { get; set; }
        public Stat WeaponKillsHandCannon { get; set; }
        public Stat WeaponKillsMachinegun { get; set; }
        public Stat WeaponKillsPulseRifle { get; set; }
        public Stat WeaponKillsRocketLauncher { get; set; }
        public Stat WeaponKillsScoutRifle { get; set; }
        public Stat WeaponKillsShotgun { get; set; }
        public Stat WeaponKillsSniper { get; set; }
        public Stat WeaponKillsSubmachinegun { get; set; }
        public Stat WeaponKillsRelic { get; set; }
        public Stat WeaponKillsSideArm { get; set; }
        public Stat WeaponKillsSword { get; set; }
        public Stat WeaponBestType { get; set; }
        public Stat AllParticipantsCount { get; set; }
        public Stat AllParticipantsTimePlayed { get; set; }
        public Stat LongestKillSpree { get; set; }
        public Stat LongestSingleLife { get; set; }
        public Stat MostPrecisionKills { get; set; }
        public Stat OrbsDropped { get; set; }
        public Stat OrbsGathered { get; set; }
        public Stat PublicEventsCompleted { get; set; }
        public Stat PublicEventsJoined { get; set; }
        public Stat RemainingTimeAfterQuitSeconds { get; set; }
        public Stat TotalActivityDurationSeconds { get; set; }
        public Stat FastestCompletion { get; set; }
        public Stat CourtOfOryxWinsTier1 { get; set; }
        public Stat CourtOfOryxWinsTier2 { get; set; }
        public Stat CourtOfOryxWinsTier3 { get; set; }
        public Stat CourtOfOryxAttempts { get; set; }
        public Stat CourtOfOryxCompletions { get; set; }
        public Stat LongestKillDistance { get; set; }
        public Stat HighestCharacterLevel { get; set; }
        public Stat HighestLightLevel { get; set; }
        public Stat ActivitiesWon { get; set; }
        public Stat Score { get; set; }
        public Stat AverageScorePerKill { get; set; }
        public Stat AverageScorePerLife { get; set; }
        public Stat BestSingleGameScore { get; set; }
        public Stat CloseCalls { get; set; }
        public Stat DominationKills { get; set; }
        public Stat WinLossRatio { get; set; }
        public Stat AllParticipantsScore { get; set; }
        public Stat DefensiveKills { get; set; }
        public Stat OffensiveKills { get; set; }
        public Stat RelicsCaptured { get; set; }
        public Stat TeamScore { get; set; }
        public Stat ZonesCaptured { get; set; }
        public Stat ZonesNeutralized { get; set; }
        public Stat CombatRating { get; set; }
    }
}
